### PR TITLE
Remove erroneous return statement check on interface transactions

### LINKED ISSUE #240: Interfaces improperly require return statements
The following fails to compile
```
interface IHash {
    transaction sha256(string message) returns string;
}

contract Hash implements IHash with java : edu.cmu.cs.obsidian.stdlib.Hash;

main contract Test {}
```

with the error:
```
 2.5: 'sha256' specifies a return type, but no return value is given.
```

Presumably this should give no error, since interfaces don't implement methods.

### PR DESCRIPTION
**Pull request by ReedOei**
In the case of interfaces, we should not require that methods be checked for a return statement. This fix simply ignores this check if the contract containing the transaction is an interface.

This closes #240.

### CODE REVIEW

File: src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala [hunk 1]
```diff
@@ -1853,22 +1853,27 @@ private def checkStatement(
...
-            val ast =
-                if (tx.body.length > 0) {
-                    tx.body.last
-                }
-                else {
-                    tx
+        lexicallyInsideOf.contract match {
+            case ObsidianContractImpl(modifiers, name, declarations, transitions, isInterface, sp) =>
+                // Don't need to check interface methods to make sure they return
+                // Use & instead of && to ensure that all conditions evaluate (hasReturn checks for multiple things)
```
Comment (mcoblenz) [inline src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala]: Interesting, but it might be better to just change the order so hasReturnStatement goes first. Then you can use &&.

Comment (ReedOei) [reply src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala]: That's how it was originally, so I just left it there (after changing it to `&&`, having thought it was a typo, and subsequently spending some time debugging it).

Comment (mcoblenz) [reply src/main/scala/edu/cmu/cs/obsidian/typecheck/Checker.scala]: I see. Still, it might be worth changing, just for uniformity and simplicity.
